### ISSUE TITLE
ADMIN-COMMIT

### ISSUE THREAD

**Issue by NicholasWahome** [THE-390-Team/THE-390#184]
These are minor modifications that have minimal impact on development and don't require review or approval. Implementing a formal review process for such changes would be time-consuming, considering the minimal alterations made. These changes primarily affect the pipeline rather than the product's code itself. Any change labeled as 'Admin Commit' is considered a direct modification to the development branch and falls into this category.

Thank you for your understanding

**Comment by patrickmac3** [comment]
approved 
these are minor changes that won't affect the functioning of the project
